vich_uploader:
    db_driver: orm

    mappings:
        book_image:
            uri_prefix: /uploads/books
            upload_destination: '%kernel.project_dir%/public/uploads/books'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

